name: 🚀 Deploy Content-Service

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host:      ${{ secrets.VM_HOST }}
          username:  ${{ secrets.VM_USER }}
          key:       ${{ secrets.VM_SSH_KEY }}
          port:      ${{ secrets.VM_SSH_PORT }}
          script: |
            set -e
            cd ~/streaming-app   # ✅ Move to repo root
            git fetch origin main
            git reset --hard origin/main

            docker compose down
            docker compose build content-service
            docker compose up -d content-service
            docker image prune -f
