name: 🚀 Deploy Gateway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy Gateway
        uses: appleboy/ssh-action@master
        with:
          host:      ${{ secrets.VM_HOST }}
          username:  ${{ secrets.VM_USER }}
          key:       ${{ secrets.VM_SSH_KEY }}
          port:      ${{ secrets.VM_SSH_PORT }}
          script: |
            set -e

            # go into the Git repo for gateway
            cd /home/opc/streaming-app/gateway

            # sync to latest main
            git fetch origin main
            git reset --hard origin/main

            # rebuild & restart only gateway
            docker compose down
            docker compose build gateway
            docker compose up -d gateway

            # optional cleanup
            docker image prune -f
